FROM amazoncorretto:21-alpine3.19 AS builder
RUN apk add --no-cache maven

WORKDIR /build
COPY pom.xml .
COPY common ./common
COPY discovery-service ./discovery-service

RUN mvn -N install
RUN mvn -f common/pom.xml clean install -DskipTests
RUN mvn -f discovery-service/pom.xml clean package -DskipTests

FROM amazoncorretto:21-alpine3.19
WORKDIR /app
COPY --from=builder /build/discovery-service/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]